### ISSUE TITLE
How to install that plugin

### ISSUE THREAD

**Issue by feikede** [CoreXDevelopment/NovaMobs#85]
Hi,
I am trying to use your plugin - thanks for that. Unfortunately it doesn't work - or I am not sure what to expect. Could you add kind of a "Installation - Doc" to your Readme.md, please. Where should the "Config" go? Where should the "Permission" go?
If everything is fine, will there be animals around my players in the nukkit world? Or should I enter "mob summon Pig" or "/mob spawn Pig"?

Thanks

**Comment by bornello** [comment]
Hi,
I am also trying to use your plugin, but it tells me that the command "mob" is unknown or that I do not have the permissions to use it. 
I can see the command on the server side, but not in the game itself.
As I could see the permission are set in the plugin.yml. Would I need to rebuild the jar against "my" nukkit.jar in order to make it work ?
Thanks,
Bornello

**Comment by countmatic** [comment]
Well, I've tried to build that plugin against the current nukkit-master branch. That fails completely for master and 1/2 branch. Don't know how they manage to build something here anyway.
I think this plugin is dead.

**Comment by bornello** [comment]
Well, i pushed the code over to CircleCI and it failed, but i figured out why:
The dependency in the pom file are referencing the jenkins at regularbox. This one demands a user name and password, so the source is not visible to the script.
Replaced the url by the following:
http://jenkins.zxda.net/job/Nukkit/lastSuccessfulBuild/maven-repository/repository/cn

At least no more source issues, now I get "real" code issues like that a class is not abstract and does not override abstract method mountEntity...

Anyways, I would not say that the plugin is dead, but under development.
Will see what I can figure out more..
I am getting back into programming after 15 years in order to teach it my 10 year old son...we have both a lot to learn :)

**Comment by bornello** [comment]
Ok, here is how to get it to work:
1.Get the latest JAR and put it into you plugins folder.
2.Start the server
3.join the server
4.in the server console type "op <yourusername>" replacing yourusername with the obvious :)
after that you can use /mob in the game
I am getting a "unable to spawn ..." message everytime, but I will figure out how that will work :)

**Comment by PikyCZ** [comment]
@bornello.. wait.. ok  this plugin have a lots of bugs and lots of features is missing.. (in github/public version :P :D)..

**Comment by PikyCZ** [comment]
@countmatic  and therefore I named the branch 1/2 1.2 update because I have not done the update yet ..

**Comment by feikede** [comment]
@bornello When you want to build the plugin, you need the Nukkit in your local maven repo. Just do mvn install (in the Nukkit repo) for that (you dont need the regularbox stuff). Afterwards you can mvn package this plugin. But there are a lot of compile errors because it's not at the same API level as Nukkit 1.0-Snapshot.
I am also trying to fix that in my branch locally.

**Comment by PikyCZ** [comment]
Just download latest from release tab and put in the plugin folder..

**Comment by feikede** [comment]
That would be fine, but the version from the release tab doesn't work at all. What is supposed to work here? In what constellation? Maybe I am on a wrong Nukkit branch? I've build the most recent from the Nukkit master branch.

**Comment by PikyCZ** [comment]
[novamobs.zip](https://github.com/CoreXDevelopment/NovaMobs/files/1450655/novamobs.zip)

**Comment by PikyCZ** [comment]
or try download latest from circle ci ..
